language: node_js

node_js:
  - '5.11'

install: ./travis/install.sh

before_script:
  - npm install -g gulp

script: ./travis/script.sh

cache:
  directories:
    - node_modules
    - bower_components
    - src/core/bower_components
    - src/admin/bower_components
    - src/admin-booking/bower_components
    - src/admin-dashboard/bower_components
    - src/events/bower_components
    - src/member/bower_components
    - src/services/bower_components
    - src/settings/bower_components

deploy:
  tags: true
  provider: s3
  bucket: angular.bookingbug.com
  region: eu-west-1
  skip_cleanup: true
  local_dir: build/booking-widget/dist
  upload_dir: $TRAVIS_TAG
  access_key_id:
    secure: VisIawQs/YP5A9bkZA1W1cIvPn0cI8dZm4QezEhMq1yCphJYnQI/x9U/vEP3P50OqNKefmMVyYLenDO6rj2RfEcprG8K6TmyIl29PEqswlXR7CtVVedBKMfWu4S3+KNkeBC/EoB4nC1ApkkDRjcDHUg56V6oDhYb1mrix0biU9Y=
  secret_access_key:
    secure: MVr4KWXdegYPDE9XJ+sMKf5Qd6OG+8SuVYKBCLOrOV9L8HSZ0hG6gCnP5k71K6z+Pa5YbLblXDbifs4vY2Bgq3vn7uPIeBVfrLyZdcIGlaGhWK047D7RvEse4JUO7vwv4HPPhzpPF/vz6isoUjeZUfqHhNC53L9E+RR/EOUGNhA=
