language: node_js

node_js:
  - '5.11'

install: ./travis/install.sh

before_script:
  - npm install -g gulp

script: ./travis/script.sh

cache:
  directories:
    - node_modules
    - bower_components
    - src/core/bower_components
    - src/admin/bower_components
    - src/admin-booking/bower_components
    - src/admin-dashboard/bower_components
    - src/events/bower_components
    - src/member/bower_components
    - src/services/bower_components
    - src/settings/bower_components

deploy:
  provider: script
  script: ./travis/deploy.sh
  skip_cleanup: true
  on:
    tags: true
  env:
    - secure: "EOLSkOnWNqKODETqXwoRK+KbxyR11YCTi8kRX0+q21KQKaTqqt39UzSOoD0qlfKXPU+D23kvWSYWcGbHQw6DiVHtenVbn9ktik3lJkscXpJmNJmaregclSYJpaK7GC5vJU0av4Q0lDASxrqBv9FftrAEoC7fTfdoZgJ8t29huoU="
