language: node_js

node_js:
  - '5.11'

install: ./travis/install.sh

before_script:
  - npm install -g gulp

script: ./travis/script.sh

cache:
  directories:
    - node_modules
    - bower_components
    - test/unit/bower_components

env:
  - secure: "JjeAjs+rZnrsIfBYo1OSszSnzRQ6Zy/BBfAvb3mE9Qf0fjDjeMy6rVbbFh/CzgJz84EuQf2iCNjWgpvoPatZfYhosiILGxRN7V35HODlenTkxuU/TSkmkkTdjDt1ijjf5dM/Er1ygrgnQO6wxyyOi9hzL70pZ3RNX6MwBn87j6A="



deploy:
  - provider: script
    script: ./travis/deploy.sh
    on:
      tags: true
    skip_cleanup: true
  - provider: script
    script: ./travis/deploy.sh
    on:
      branch: master
    skip_cleanup: true

