language: node_js
node_js:
- '0.10'
before_script:
- npm install -g gulp
script:
- gulp test
- gulp buildWidget
cache:
  directories:
  - node_modules
  - bower_components
deploy:
  provider: s3
  bucket: angular.bookingbug.com
  region: eu-west-1
  skip_cleanup: true
  local_dir: build/booking-widget/dist
  upload_dir: head
  access_key_id:
    secure: VisIawQs/YP5A9bkZA1W1cIvPn0cI8dZm4QezEhMq1yCphJYnQI/x9U/vEP3P50OqNKefmMVyYLenDO6rj2RfEcprG8K6TmyIl29PEqswlXR7CtVVedBKMfWu4S3+KNkeBC/EoB4nC1ApkkDRjcDHUg56V6oDhYb1mrix0biU9Y=
  secret_access_key:
    secure: MVr4KWXdegYPDE9XJ+sMKf5Qd6OG+8SuVYKBCLOrOV9L8HSZ0hG6gCnP5k71K6z+Pa5YbLblXDbifs4vY2Bgq3vn7uPIeBVfrLyZdcIGlaGhWK047D7RvEse4JUO7vwv4HPPhzpPF/vz6isoUjeZUfqHhNC53L9E+RR/EOUGNhA=
