language: node_js
env:
  global:
    - secure: "STfahM2WRSe+YRXjdbF1dkTY+5yrsaWd2DUjktmzOkK35IWODAxvaWB04IzfPYAbJ/MR8Iw7RNwdPAhIvPm1WSMXCGK053oSpYqZzrD7NXpU1AXlaHIe/3af8iZFhnZODjgnJ8B+y3AQ/0fC/dlimYh1+XXuhXISRGZZ9oy+Jqk="
node_js:
  - "5.1"
before_script:
  - npm install -g gulp
script: gulp test
cache:
  directories:
    - node_modules
    - bower_components
